### ISSUE TITLE
Annotated MS/MS spectra

### ISSUE THREAD

**Issue by oliverschilling** [thomasp85/MSGFgui#33]
Hello,

Thank you for developing msgfgui. I manually parsed through an msgf result file (mzident format) and I could not find the " section" with the information about the fragment assignments. How does msgfgui retrieve this information? Thanks for your support

Oliver

**Comment by thomasp85** [comment]
Hi Oliver

The fragmentation information is calculated ad hoc when you select a spectrum. If you already got the suspected peptide sequence it is straightforward(-ish) to assign identity to the different peaks - see e.g. http://www.ionsource.com/tutorial/DeNovo/DeNovoTOC.htm

Hope this helps
